# Generated by Django 4.1.4 on 2022-12-14 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderMovieSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gender_movie_serie',
            },
        ),
        migrations.CreateModel(
            name='MovieSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('type_streaming', models.CharField(choices=[('Serie', 'Serie'), ('Pelicula', 'Pelicula')], max_length=150)),
                ('num_views', models.IntegerField()),
                ('average', models.IntegerField(default=0)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_type_gender', to='movies.gendermovieseries')),
            ],
            options={
                'verbose_name': 'Peliculas y Series',
                'verbose_name_plural': 'Peliculas y Series',
                'db_table': 'movie_series',
            },
        ),
        migrations.CreateModel(
            name='ScoreMovieSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('score', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('movie_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_movie_serie', to='movies.movieseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_movie_series_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'score_movie_serie',
            },
        ),
    ]
