# Generated by Django 4.1.4 on 2022-12-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseries',
            name='average',
            field=models.FloatField(default=0),
        ),
    ]
