# Generated by Django 4.1.4 on 2022-12-14 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_alter_movieseries_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieseries',
            name='num_views',
        ),
        migrations.CreateModel(
            name='ViewsMoviesSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('movie_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_movie_serie', to='movies.movieseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_movie_series_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'view_movie_serie',
            },
        ),
    ]
