# Generated by Django 4.1.4 on 2022-12-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movieseries_num_views_viewsmoviesseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseries',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/movie-series/'),
        ),
    ]
